print("Initial Tuple-:")
tuplex = (2, 4, 5, 6, 2, 3, 4, 4, 7) 
print(tuplex)
print("After counting the Element's")
count = tuplex.count(1)
print(1," ",count)
count = tuplex.count(2)
print(2," ",count)
count = tuplex.count(3)
print(3," ",count)
count = tuplex.count(4)
print(4," ",count)
count = tuplex.count(5)
print(5," ",count)
count = tuplex.count(6)
print(6," ",count)
count = tuplex.count(7)
print(7," ",count)

